/* Counter POS interaction study. In-memory synthetic data only. No backend, real payment,
   service worker, authentication or durable transaction storage. Refresh resets all state.
   Screenshot routes: ?screen=pos|products|inventory|sales|dashboard|sync|shift|settings|login
   Overlay routes: ?screen=payment|receipt|cart ; optional &offline=1. */
'use strict';
const I={sell:'M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z',products:'M4 7l8-4 8 4v10l-8 4-8-4z M4 7l8 4 8-4 M12 11v10',inventory:'M3 8l9-5 9 5-9 5z M3 12l9 5 9-5 M3 16l9 5 9-5',sales:'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 7h6 M9 11h6 M9 15h4',dashboard:'M4 20V11h4v9 M10 20V4h4v16 M16 20v-7h4v7',sync:'M20 7v5h-5 M4 17v-5h5 M5 8a7 7 0 0112-3l3 4 M19 16a7 7 0 01-12 3l-3-4',shift:'M4 7h16v13H4z M8 7V4h8v3 M4 12h16 M10 16h4',settings:'M12 8a4 4 0 100 8 4 4 0 000-8 M10 3h4l1 3 3 1 3-1 1 4-2 2v3l2 2-2 4-3-1-3 1-1 3h-4l-1-3-3-1-3 1-2-4 2-2v-3L2 10l1-4 3 1 3-1z',search:'M10.5 3.5a7 7 0 100 14 7 7 0 000-14 M16 16l5 5',scan:'M4 8V4h4 M16 4h4v4 M20 16v4h-4 M8 20H4v-4 M8 8v8 M11 8v8 M14 8v8 M17 8v8',arrow:'M5 12h14 M14 7l5 5-5 5',check:'M5 12l4 4L19 6',cash:'M3 6h18v12H3z M12 9a3 3 0 100 6 3 3 0 000-6 M6 9v6 M18 9v6',card:'M3 5h18v14H3z M3 10h18 M6 15h4',qr:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h2v2h4v4h-6z',close:'M6 6l12 12 M18 6L6 18',print:'M6 8V3h12v5 M6 17H3V8h18v9h-3 M6 13h12v8H6z',clock:'M12 3a9 9 0 100 18 9 9 0 000-18 M12 7v5l3 2',info:'M12 3a9 9 0 100 18 9 9 0 000-18 M12 10v6 M12 7h.01',back:'M19 12H5 M10 7l-5 5 5 5',plus:'M12 5v14 M5 12h14',lock:'M7 10V7a5 5 0 0110 0v3 M5 10h14v11H5z'};
function icon(n,size=20){return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${I[n]||I.products}"/></svg>`;}
function brand(){return `<div class="brand"><span class="brandmark">${icon('sell',21)}</span><div class="brandword">counter<small>POINT OF SALE</small></div></div>`;}
const products=[
{id:1,name:'Cold Brew',sku:'DRK-001',category:'Drinks',price:450,cost:210,stock:24,tone:'#eee6da',kind:'coffee'},
{id:2,name:'Oat Cookies',sku:'SNK-001',category:'Snacks',price:320,cost:140,stock:18,tone:'#f0e9db',kind:'cookies'},
{id:3,name:'Sparkling Water',sku:'DRK-002',category:'Drinks',price:180,cost:65,stock:32,tone:'#e3edf0',kind:'water'},
{id:4,name:'Matcha Latte',sku:'DRK-003',category:'Drinks',price:490,cost:230,stock:12,tone:'#e6edda',kind:'matcha'},
{id:5,name:'Sourdough Roll',sku:'FD-001',category:'Bakery',price:260,cost:110,stock:9,tone:'#f3e5d6',kind:'bread'},
{id:6,name:'Orange Juice',sku:'DRK-004',category:'Drinks',price:350,cost:155,stock:16,tone:'#f6ecd3',kind:'juice'},
{id:7,name:'Dark Chocolate',sku:'SNK-002',category:'Snacks',price:420,cost:190,stock:21,tone:'#eadfe0',kind:'chocolate'},
{id:8,name:'Fresh Milk',sku:'DRK-005',category:'Drinks',price:290,cost:140,stock:4,tone:'#e0eae7',kind:'milk'},
{id:9,name:'Jasmine Tea',sku:'DRK-006',category:'Drinks',price:280,cost:120,stock:15,tone:'#e9ebd6',kind:'tea'},
{id:10,name:'Sea Salt Chips',sku:'SNK-003',category:'Snacks',price:240,cost:95,stock:27,tone:'#ece5dc',kind:'chips'},
{id:11,name:'Hand Wash',sku:'HM-001',category:'Essentials',price:650,cost:310,stock:6,tone:'#e4e4ed',kind:'soap'},
{id:12,name:'Pocket Notebook',sku:'HM-002',category:'Essentials',price:390,cost:160,stock:14,tone:'#e1e8ee',kind:'book'}];
function art(p){let a='';const k=p.kind;
if(['coffee','matcha'].includes(k))a=`<path d="M32 35h47l-5 62H38z" fill="${k==='coffee'?'#684430':'#8aa56e'}"/><path d="M39 39h6l4 52h-8z" fill="#fff" opacity=".18"/><rect x="28" y="27" width="55" height="9" rx="4" fill="#342d2a"/><rect x="34" y="21" width="44" height="9" rx="4" fill="#443c35"/><rect x="36" y="52" width="39" height="28" rx="2" fill="#f9f4e6"/><path d="M50 61c6-9 14-2 10 4s-12 8-10-4z" fill="${k==='coffee'?'#76533c':'#648055'}"/>`;
else if(['water','juice','tea'].includes(k)){let col=k==='water'?'#91bacb':k==='juice'?'#dfa839':'#a8b375';a=`<rect x="46" y="18" width="20" height="13" rx="3" fill="${k==='water'?'#436d7b':'#697556'}"/><path d="M44 31h24l10 14v51q0 6-8 6H42q-8 0-8-6V45z" fill="${col}"/><path d="M40 43v47" stroke="#fff" stroke-width="5" opacity=".4"/><rect x="35" y="57" width="42" height="29" rx="2" fill="#f4f5e9"/><path d="M48 70q10-14 17 0-9 13-17 0" fill="${k==='water'?'#628896':k==='juice'?'#cf9c24':'#758a4d'}"/>`;}
else if(k==='cookies')a='<path d="M29 21h54l-3 80H32z" fill="#b49462"/><path d="M29 21h54v9H29z M31 91h50v10H31z" fill="#846b42"/><rect x="31" y="41" width="50" height="42" fill="#f4eddb"/><circle cx="56" cy="64" r="16" fill="#c2965d"/><g fill="#6e4a34"><circle cx="50" cy="60" r="2.5"/><circle cx="61" cy="64" r="2"/><circle cx="51" cy="70" r="2"/><circle cx="62" cy="54" r="2"/></g>';
else if(k==='bread')a='<g transform="rotate(-26 56 64)"><rect x="25" y="31" width="63" height="62" rx="27" fill="#b98043"/><rect x="28" y="27" width="57" height="61" rx="26" fill="#dfb473"/><path d="M39 43l12 8 M52 35l14 10 M68 42l10 9" stroke="#f7dc9d" stroke-width="6" stroke-linecap="round"/></g>';
else if(k==='chocolate')a='<g transform="rotate(8 56 60)"><rect x="31" y="18" width="50" height="84" rx="3" fill="#4f3534"/><path d="M34 22h44v38H34z" fill="#755047"/><path d="M49 22v38 M64 22v38 M34 35h44 M34 48h44" stroke="#4f3534" stroke-width="2"/><path d="M31 51l50 7v44H31z" fill="#8f5d68"/><rect x="39" y="67" width="34" height="18" fill="#ebdfd3"/><path d="M45 76h22" stroke="#94696b" stroke-width="3"/></g>';
else if(k==='milk')a='<path d="M36 34l10-15h23l10 15v68H36z" fill="#f3f3df"/><path d="M36 34h43v68H36z" fill="#afc6bc"/><path d="M46 19v14h33L69 19z" fill="#55756d"/><path d="M59 34v68h20V34z" fill="#92b0a5"/><rect x="38" y="52" width="37" height="27" rx="2" fill="#f8f4e8"/><path d="M53 58q-11 13 0 14 11-1 0-14" fill="#82a69b"/>';
else if(k==='chips')a='<path d="M31 21h50l-3 13 7 67H27l8-67z" fill="#ba9d76"/><path d="M31 21h50v8H31z M27 95h58v6H27z" fill="#8c7051"/><rect x="32" y="41" width="49" height="39" fill="#eee8d7"/><ellipse cx="50" cy="59" rx="11" ry="8" fill="#d4b47a"/><ellipse cx="64" cy="66" rx="11" ry="7" fill="#e4c694"/>';
else if(k==='soap')a='<path d="M50 19h29v6H61v14H50z" fill="#5d627d"/><rect x="36" y="36" width="44" height="67" rx="10" fill="#9ba0b6"/><path d="M42 45v48" stroke="#fff" opacity=".3" stroke-width="5"/><rect x="36" y="58" width="44" height="27" fill="#eeecf1"/><path d="M58 62q-10 14 0 15 10-1 0-15" fill="#777d9d"/>';
else a='<g transform="rotate(-8 56 60)"><rect x="30" y="19" width="57" height="84" rx="4" fill="#4d7187"/><rect x="27" y="16" width="57" height="83" rx="4" fill="#809eaf"/><path d="M35 17v81" stroke="#45677e" stroke-width="3"/><rect x="43" y="36" width="30" height="24" rx="2" fill="#e8edea"/><path d="M48 43h19 M48 48h19 M48 53h12" stroke="#b5c6ce" stroke-width="2"/><path d="M76 17v81" stroke="#caaf72" stroke-width="3"/></g>';
return `<svg viewBox="0 0 112 120" aria-hidden="true"><ellipse cx="56" cy="107" rx="29" ry="5" fill="#193f3520"/>${a}</svg>`;}
const fmt=n=>'S$'+(n/100).toFixed(2),compact=n=>(n/100).toFixed(2),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qs=new URLSearchParams(window.__DESIGN_QUERY__||location.search),initial=qs.get('screen')||'pos';
let state={screen:['payment','receipt','cart'].includes(initial)?'pos':initial,cart:{1:2,2:1,3:1},category:'All items',search:'',offline:qs.has('offline'),overlay:initial==='payment'?'payment':initial==='receipt'?'receipt':null,mobileCart:initial==='cart',tender:2000,receipt:null};
function total(){return Object.entries(state.cart).reduce((s,[id,q])=>s+products.find(p=>p.id===+id).price*q,0)}
function units(){return Object.values(state.cart).reduce((a,b)=>a+b,0)}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.style.display='none',2800)}
function navButton(key,label){return `<button data-nav="${key}" class="${state.screen===key?'active':''}">${icon(key)}<span>${label}</span></button>`}
function status(){return `<button class="badge ${state.offline?'warn':''}" data-action="offline" title="Toggle simulated connectivity; no actual network state changes"><span class="dot"></span>${state.offline?'Offline · 3 pending':'Online · Synced'}</button>`}
function mobileNav(){return `<div class="mobile-nav"><label for="view-select" class="small muted">View &nbsp;</label><select id="view-select">${['pos','products','inventory','sales','dashboard','sync','shift','settings'].map(x=>`<option value="${x}" ${x===state.screen?'selected':''}>${({pos:'Sell',dashboard:'Overview',shift:'Close shift'})[x]||x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></div>`}
function shell(){let title={pos:'Sell',products:'Products',inventory:'Inventory',sales:'Sales history',dashboard:'Overview',sync:'Sync center',shift:'Close shift',settings:'Settings'}[state.screen]||'Sell';return `<div class="study">INTERACTION STUDY · Synthetic data · No real payments <span>Counter POS / Proposed V1 / 02 OCT 2026</span></div><div class="app"><aside class="rail">${brand()}<nav class="nav" aria-label="Main navigation">${navButton('pos','Sell').replace(icon('pos'),icon('sell'))}${navButton('products','Products')}${navButton('inventory','Inventory')}${navButton('sales','Sales')}${navButton('dashboard','Overview')}</nav><div class="rail-bottom"><div><p class="rail-label">WORKSPACE</p><nav class="nav">${navButton('sync','Sync center')}${navButton('shift','Close shift')}${navButton('settings','Settings')}</nav></div><div class="store"><strong>Everyday Store</strong><br><span class="muted">Terminal 01 · Shift 024</span><br><span style="color:var(--teal)"><span class="dot"></span>Shift open</span></div></div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">EVERYDAY STORE / TERMINAL 01</p><h1>${title}</h1></div><div class="top-actions">${status()}<div class="cashier"><span class="avatar">${state.screen==='pos'||state.screen==='shift'?'AL':'MG'}</span><div class="usertext"><strong>${state.screen==='pos'||state.screen==='shift'?'Alex':'Morgan'}</strong><p class="muted small">${state.screen==='pos'||state.screen==='shift'?'Cashier':'Manager'}</p></div></div></div></header><main class="main">${state.screen==='pos'?sell():backoffice()}</main></section></div>${state.mobileCart?order(true):''}${state.overlay?overlay():''}`;}
function sell(){return `<div class="sell-layout"><section class="catalogue">${state.offline?`<div class="offline-alert"><strong>Offline simulation.</strong> Cash only. Previously saved sales wait for foreground sync.</div>`:''}<div class="catalogue-header"><label class="search">${icon('search',19)}<input id="search" aria-label="Search products" placeholder="Search products or scan a barcode" value="${esc(state.search)}"><span class="key">⌘ K</span></label><button class="iconbutton" data-action="scan" aria-label="Barcode help">${icon('scan')}</button></div><div class="chips">${['All items','Drinks','Snacks','Bakery','Essentials'].map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="countline"><span>Quick picks</span><span>12 products · Tax off</span></div><div class="products-grid" id="product-grid">${productGrid()}</div><p class="footnote">Tap a product to add it. Stock shown is a synthetic design fixture.</p></section>${order(false)}</div><div class="mobile-order"><button class="primary" data-action="cart"><span>View order <span style="opacity:.65">· ${units()} items</span></span><span>${fmt(total())} ${icon('arrow',17)}</span></button></div>`;}
function productGrid(){let list=products.filter(p=>(state.category==='All items'||p.category===state.category)&&(`${p.name} ${p.sku}`.toLowerCase().includes(state.search.toLowerCase())));return list.map(p=>`<button class="product" data-add="${p.id}" aria-label="Add ${p.name}, ${fmt(p.price)}"><div class="art" style="--tone:${p.tone}">${art(p)}${state.cart[p.id]?`<span class="selected-count">${state.cart[p.id]}</span>`:''}</div><h3>${p.name}</h3><div class="product-foot"><span class="product-price">${fmt(p.price)}</span><span class="stock ${p.stock<7?'low':''}">${p.stock<7?'Low · ':''}${p.stock} left</span></div></button>`).join('')||'<p class="no-results">No products match. Try a name or SKU.</p>';}
function order(mobile){return `<aside class="order ${mobile?'mobile-expanded':''}" aria-label="Current order"><div class="order-head"><div><h2>Current order</h2><span class="small muted">Walk-in customer · ${units()} items</span></div><button class="text-button" data-action="${mobile?'closecart':'clear'}" aria-label="${mobile?'Close order':'Clear current order'}">${mobile?icon('close'):'Clear'}</button></div><div class="order-meta"><span>Order #024-018</span><button class="text-button" style="padding:0;min-height:44px" data-action="hold">Hold order</button></div><div class="cart-lines">${cartLines()}</div><div class="totals"><div class="total-line"><span class="muted">Subtotal</span><span>${fmt(total())}</span></div><div class="total-line"><span class="muted">Discount</span><span>S$0.00</span></div><div class="total-line"><span class="muted">Tax <span class="small">(not enabled)</span></span><span>S$0.00</span></div><div class="grand"><span>Total <span class="small muted">SGD</span></span><strong>${fmt(total())}</strong></div></div><button class="primary pay" data-action="pay" ${!units()?'disabled':''}><span>Take payment</span><span>${fmt(total())} ${icon('arrow',17)}</span></button><p class="helper">Prototype only — no server sale or payment.</p></aside>`;}
function cartLines(){return Object.entries(state.cart).map(([id,q])=>{let p=products.find(p=>p.id===+id);return `<div class="cart-line"><div class="mini-art" style="--tone:${p.tone}">${art(p)}</div><div><div class="line-top"><div><h3>${p.name}</h3><span class="muted small">${fmt(p.price)} each</span></div><span class="line-price">${fmt(p.price*q)}</span></div><div class="qtyline"><div class="qty"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease ${p.name}">−</button><span>${q}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase ${p.name}">+</button></div><button class="text-button" data-remove="${p.id}" aria-label="Remove ${p.name}">Remove</button></div></div></div>`}).join('')||'<div class="empty">Your order is empty.<br>Choose a product to begin.</div>';}
function stat(label,value,note){return `<div class="stat"><p class="label">${label}</p><div class="value">${value}</div><span class="note">${note}</span></div>`}
function pcell(p){return `<div class="productcell"><span class="mini-art" style="--tone:${p.tone}">${art(p)}</span><span><strong>${p.name}</strong><small>${p.sku}</small></span></div>`}
function basicHead(title,sub,action=''){return `<div class="section-head"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>`}
function readonly(label,ic='plus'){return `<button class="primary" data-action="readonly">${icon(ic,17)} ${label}</button>`}
function table(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function backoffice(){let content='';
if(state.screen==='products'){content=basicHead('Your product catalogue','Simple products. Clear prices. Stock lives in the ledger.',readonly('Add product'))+`<div class="stats">${stat('Active products','12','Across 4 categories')}${stat('Low-stock items','2','Fresh Milk · Hand Wash')}${stat('Price revisions','16','History is preserved')}${stat('Catalogue status','Current','Synthetic snapshot v12')}</div><div class="panel"><div class="filters"><div class="search">${icon('search',18)}<input placeholder="Search name, SKU or barcode" aria-label="Catalogue study search" disabled></div><button class="secondary" data-action="readonly">All categories</button><button class="secondary" data-action="readonly">Active</button></div>${table(['Product','Category','Selling price','On hand','Status',''],products.slice(0,7).map(p=>[pcell(p),p.category,fmt(p.price),p.stock,`<span class="badge ${p.stock<7?'warn':''}">${p.stock<7?'Low stock':'Active'}</span>`,'<span class="row-actions">Edit →</span>']))}</div>`;}
if(state.screen==='inventory'){content=basicHead('Inventory ledger','Every quantity has a reason and a reference.',readonly('Receive stock'))+`<div class="stats">${stat('Units on hand','198','Current synthetic balance')}${stat('Low-stock items','2','Reorder attention needed')}${stat('Stock received','60','Today · sample ledger')}${stat('Adjustments','1','Manager recorded')}</div><div class="split-panels"><div class="panel"><h3>Recent movements</h3>${table(['Product','Movement','Quantity','Reference'],[[pcell(products[0]),'<span class="badge neutral">Sale</span>','−2','CP-000018'],[pcell(products[1]),'<span class="badge neutral">Sale</span>','−1','CP-000018'],[pcell(products[2]),'<span class="badge neutral">Sale</span>','−1','CP-000018'],[pcell(products[7]),'<span class="badge warn">Adjustment</span>','−1','ADJ-0003'],[pcell(products[3]),'<span class="badge">Receipt</span>','+20','RCV-0007']])}</div><div class="panel"><h3>Count an item</h3><div class="field"><label>Product</label><select disabled><option>Fresh Milk · DRK-005</option></select></div><div class="twocol"><div class="field"><label>Recorded stock</label><input value="4" readonly></div><div class="field"><label>Counted stock</label><input value="3" readonly></div></div><div class="banner">Adjustment preview: <strong>−1 unit</strong></div><div class="field"><label>Reason</label><input value="Damaged pack" readonly><p class="help">A reason and current balance version are required.</p></div><button class="primary full" data-action="readonly">Review adjustment</button><p class="footnote">Manager only · Online required<br>Creates a movement, not a direct stock overwrite.</p></div></div>`;}
if(state.screen==='sales'){content=basicHead('Sales history','Posted sales remain unchanged. Returns create linked records.','<button class="secondary" data-action="readonly">Export CSV</button>')+`<div class="stats">${stat('Gross sales','S$486.00','Before refunds')}${stat('Refunds','S$18.00','Recognized today')}${stat('Net sales','S$468.00','Gross less refunds')}${stat('Completed orders','36','Synthetic daily data')}</div><div class="panel"><div class="filters"><div class="search">${icon('search',18)}<input placeholder="Find a receipt" disabled aria-label="Receipt search study"></div><button class="secondary" data-action="readonly">02 Oct 2026</button><button class="secondary" data-action="readonly">All methods</button></div>${table(['Receipt','Time','Method','Items','Total','State',''],[['CP-000018','14:32','Cash','4','S$14.00','<span class="badge">Posted</span>','View →'],['CP-000017','14:26','Card · manual','3','S$12.90','<span class="badge">Posted</span>','View →'],['CP-000016','14:18','Cash','2','S$7.70','<span class="badge">Posted</span>','View →'],['CP-000015','14:05','PayNow · manual','5','S$19.60','<span class="badge">Posted</span>','View →'],['CP-000014','13:54','Cash','3','S$11.20','<span class="badge warn">Part returned</span>','View →'],['CP-000013','13:41','Cash','1','S$4.50','<span class="badge">Posted</span>','View →']])}<p class="footnote">Manual methods are operator-recorded external payments, not provider-verified transactions. Listed rows are a subset of the synthetic daily summary.</p></div>`;}
if(state.screen==='dashboard'){content=basicHead('A clear view of today','02 October 2026 · Server-confirmed synthetic sales only','<button class="secondary" data-action="readonly">Today ▾</button>')+`<div class="stats">${stat('Gross sales','S$486.00','36 completed orders')}${stat('Refunds','S$18.00','2 return records')}${stat('Net sales','S$468.00','Gross less refunds')}${stat('Average ticket','S$13.50','Gross / completed orders')}</div><div class="split-panels"><div class="panel"><div class="charttitle"><h3>Sales through the day</h3><span class="small muted">Illustrative hourly shape</span></div><div class="bars">${[28,45,62,88,76,94,63,80].map((h,i)=>`<div class="bar ${i===5?'highlight':''}" style="height:${h}%"><span>${9+i}:00</span></div>`).join('')}</div><p class="footnote">Illustrative design visualization; not an analytic dataset.</p></div><div class="panel"><h3>Most purchased</h3>${[products[0],products[2],products[1],products[5]].map((p,i)=>`<div class="rank"><span class="rank-no">0${i+1}</span><strong>${p.name}</strong><span class="small muted">${[22,18,14,11][i]} units</span></div>`).join('')}</div></div><div class="panel"><h3>Needs attention</h3><div class="twocol"><div class="banner">${icon('info')}<div><strong>2 products are running low</strong><br>Fresh Milk: 4 · Hand Wash: 6</div></div><div style="padding:16px"><span class="badge"><span class="dot"></span>All sample sales synced</span><p class="footnote">Pending local amounts must be shown separately from confirmed reports.</p></div></div></div>`;}
if(state.screen==='sync'){content=basicHead('See what is waiting to sync','Review what is saved locally and what the server has acknowledged.','<button class="secondary" data-action="sync">'+icon('sync',17)+' Retry sync</button>')+`<div class="banner">${icon('info')}<div><strong>Offline simulation · 3 sales waiting</strong><br>Keep this device's data. Reopen the app when connected to complete foreground sync.</div></div><div class="stats">${stat('Pending sales','3','Saved on this device')}${stat('Pending amount','S$32.20','Not in confirmed totals')}${stat('Needs review','0','No sample conflicts')}${stat('Last server sync','14:24','Sample timestamp')}</div><div class="panel"><h3>Pending documents</h3>${[['LOCAL-T01-018','S$14.00','14:32'],['LOCAL-T01-019','S$7.70','14:35'],['LOCAL-T01-020','S$10.50','14:38']].map(r=>`<div class="syncrow"><strong>${r[0]}</strong><span>${r[1]} · Cash</span><span class="muted">Saved ${r[2]}</span><span class="badge warn">Pending</span></div>`).join('')}<p class="footnote">Retry reuses the same transaction UUID. An acknowledgement never creates a second stock deduction.</p></div><div class="panel"><h3>Safe recovery</h3><div class="step"><i>1</i> Restore connectivity and reauthenticate if asked.</div><div class="step"><i>2</i> Retry the unchanged documents; keep the app open.</div><div class="step"><i>3</i> Ask a manager to export a recovery copy if a conflict persists.</div></div>`;}
if(state.screen==='shift'){content=basicHead('Close shift 024','Terminal 01 · Alex · Opened at 09:00', '<span class="badge">Ready to reconcile</span>')+`<div class="twocol"><div class="panel"><h3>Expected cash</h3>${[['Opening float','S$100.00'],['Cash sales applied','S$286.00'],['Cash refunds','−S$18.00'],['Cash in','S$0.00'],['Cash out','−S$20.00']].map(r=>`<div class="payment-summary"><span class="muted">${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}<div class="grand"><span>Expected drawer</span><strong>S$348.00</strong></div><p class="footnote">Change is already excluded from cash applied.<br>This shift fixture is consistent with the daily totals.</p></div><div class="panel"><h3>Count the drawer</h3><div class="field"><label>Actual cash count (SGD)</label><input value="348.00" readonly></div><div class="change-box"><span>Difference</span><strong>S$0.00</strong></div><div class="step"><i>✓</i> No pending or review documents</div><div class="step"><i>✓</i> Server reconciliation acknowledged</div><button class="primary full" data-action="readonly">Confirm close shift</button><p class="footnote">Online required. A local cash-count draft is not a closed shift.</p></div></div>`;}
if(state.screen==='settings'){content=basicHead('Store & device','Small configuration surface. Important changes stay auditable.')+`<div class="twocol"><div class="panel"><h3>Store preferences</h3>${[['Store','Everyday Store'],['Currency','SGD · Locked after first sale'],['Timezone','Asia/Singapore'],['Tax','Disabled · Demo configuration'],['Receipt','80mm browser print']].map(r=>`<div class="settings-row"><div><strong>${r[0]}</strong><p>${r[1]}</p></div><button class="text-button" data-action="readonly">Review</button></div>`).join('')}</div><div><div class="panel"><h3>App lifecycle</h3><span class="badge neutral">Design build 1.0</span><div class="settings-row"><div><strong>New version available</strong><p>Activate only when checkout and outbox are safe.</p></div></div><button class="primary full" style="margin-top:20px" data-action="update">Review update</button><p class="footnote">Prototype illustration only. No service worker is registered.</p></div><div class="panel"><h3>Backup & recovery</h3><p class="small muted" style="line-height:1.8">Server backups and pending-device recovery are separate responsibilities. Test a restore before pilot use.</p><button class="secondary" style="margin-top:20px" data-action="readonly">View recovery guide</button></div></div></div>`;}
return `<section class="backoffice">${mobileNav()}${content}<p class="screen-disclaimer">Design study · Synthetic data · Administrative controls are read-only in this prototype.</p></section>`;}
function overlay(){if(state.overlay==='payment')return `<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="payment-title"><div class="dialog-header"><div><p class="eyebrow">ORDER #024-018</p><h2 id="payment-title">Take payment</h2></div><button class="iconbutton" data-action="closeoverlay" aria-label="Close payment">${icon('close')}</button></div><div class="payment-layout"><div class="payment-left"><div class="due-box"><p>Amount due · SGD</p><strong>${fmt(total())}</strong><small>${units()} items · Tax not enabled</small></div>${Object.entries(state.cart).map(([id,q])=>{let p=products.find(p=>p.id===+id);return `<div class="payment-summary"><span>${q} × ${p.name}</span><strong>${fmt(p.price*q)}</strong></div>`}).join('')}<p class="payment-note">Review the order before taking money. The prototype simulates a cash receipt only.</p></div><div><p class="small muted">Payment method</p><div class="method-row"><button class="selected">${icon('cash')}<br>Cash<small>Cashier confirms</small></button><button data-action="external" ${state.offline?'disabled':''}>${icon('card')}<br>Card<small>External · manual</small></button><button data-action="external" ${state.offline?'disabled':''}>${icon('qr')}<br>PayNow<small>External · manual</small></button></div><div class="field"><label for="tender">Cash received (SGD)</label><input class="tender-input" id="tender" inputmode="decimal" value="${compact(state.tender)}" autocomplete="off"></div><div class="quickcash"><button data-cash="${total()}">Exact</button><button data-cash="2000">S$20</button><button data-cash="5000">S$50</button></div><div class="change-box"><span>Change to return</span><strong id="change">${fmt(Math.max(0,state.tender-total()))}</strong></div><button id="confirm-payment" class="primary full" data-action="confirm" ${state.tender<total()?'disabled':''}>${icon('check',18)} Confirm simulated cash sale</button><p class="payment-note">No money moves. No server sale is created. ${state.offline?'Offline mode is a visual simulation.':'External payment options are not implemented here.'}</p></div></div></section></div>`;
let r=state.receipt||{total:total(),tender:state.tender,cart:{...state.cart}},number=state.offline?'LOCAL-T01-018':'CP-000018';return `<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="receipt-title"><div class="dialog-header"><span class="eyebrow">SIMULATED RECEIPT</span><button class="iconbutton" data-action="closeoverlay" aria-label="Close receipt">${icon('close')}</button></div><div class="receipt-wrap"><div class="success"><div class="success-icon">${icon('check',32)}</div><h2 id="receipt-title">Sale preview complete</h2><p>Cash received ${fmt(r.tender)}.<br>Return <strong style="color:var(--ink)">${fmt(r.tender-r.total)}</strong> in change.</p><span class="badge ${state.offline?'warn':'neutral'}">${state.offline?'Saved locally · Simulated':'Demo only · No server record'}</span><button class="primary full" data-action="new">Start a new order ${icon('arrow',18)}</button><button class="secondary full" style="margin-top:10px" data-action="print">${icon('print',17)} Print preview</button><p class="footnote">Printing or reprinting must never create another sale.<br>This receipt is sample data, not a tax invoice.</p></div><div class="receipt"><h3>EVERYDAY STORE</h3><p class="center">COUNTER POS · DEMO<br>02 OCT 2026 · 14:32<br>${number}</p><hr>${Object.entries(r.cart).map(([id,q])=>{let p=products.find(p=>p.id===+id);return `<div class="receipt-line"><span>${q} × ${p.name}</span><span>${compact(q*p.price)}</span></div>`}).join('')}<hr><div class="receipt-line"><span>Subtotal</span><span>${compact(r.total)}</span></div><div class="receipt-line"><span>Tax (off)</span><span>0.00</span></div><div class="receipt-line"><strong>TOTAL SGD</strong><strong>${compact(r.total)}</strong></div><hr><div class="receipt-line"><span>Cash received</span><span>${compact(r.tender)}</span></div><div class="receipt-line"><span>Change</span><span>${compact(r.tender-r.total)}</span></div><p class="center" style="margin-top:24px">Thank you. See you again.<br><span style="font-size:10px">SYNTHETIC · NOT A TAX INVOICE</span></p></div></div></section></div>`;}
function login(){return `<div class="study">INTERACTION STUDY · Synthetic data · No real authentication</div><div class="login"><div class="login-art">${brand()}<div><p class="eyebrow" style="color:#91b9ac">A CALMER WAY TO SELL</p><h1>A small counter.<br>A complete day.</h1><p>Products, sales and stock, together.<br>A focused workspace for everyday retail.</p><div class="login-visual">${[products[1],products[0],products[2]].map(p=>`<div class="tile">${art(p)}</div>`).join('')}</div></div><p class="small">Single-store focus · Cash-first offline design</p></div><div class="login-form"><p class="eyebrow">COUNTER POS / EVERYDAY STORE</p><h2>Open your workspace</h2><p>In the proposed application, sign in online and verify this terminal before opening a shift.</p><div class="field"><label>Workspace</label><input value="Everyday Store — demo" readonly></div><div class="field"><label>Operator</label><input value="Alex — synthetic cashier" readonly></div><div class="field"><label>Opening float (SGD)</label><input value="100.00" readonly></div><button class="primary full" data-action="enter">Enter design demo ${icon('arrow',17)}</button><p class="footnote" style="margin-top:18px">No account or password is collected.<br>This study is not a deployed POS.</p></div></div>`;}
function render(){document.getElementById('root').innerHTML=state.screen==='login'?login():shell();bind();if(state.overlay){setTimeout(()=>{document.querySelector('.dialog button')?.focus({preventScroll:true})},0)}}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.nav;state.mobileCart=false;state.overlay=null;render()});document.querySelector('#view-select')?.addEventListener('change',e=>{state.screen=e.target.value;render()});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render()});document.querySelector('#search')?.addEventListener('input',e=>{state.search=e.target.value;document.querySelector('#product-grid').innerHTML=productGrid();bindProduct()});bindProduct();document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{let id=b.dataset.qty;state.cart[id]=Math.max(0,Math.min(99,(state.cart[id]||0)+(+b.dataset.delta)));if(!state.cart[id])delete state.cart[id];render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{delete state.cart[b.dataset.remove];render()});document.querySelectorAll('[data-cash]').forEach(b=>b.onclick=()=>{state.tender=+b.dataset.cash;render()});document.querySelector('#tender')?.addEventListener('input',e=>{let raw=e.target.value.trim();state.tender=/^\d+(\.\d{0,2})?$/.test(raw)?Math.round(Number(raw)*100):-1;document.querySelector('#change').textContent=state.tender>=0?fmt(Math.max(0,state.tender-total())):'Invalid amount';document.querySelector('#confirm-payment').disabled=state.tender<total()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));}
function bindProduct(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const id=+b.dataset.add;state.cart[id]=Math.min(99,(state.cart[id]||0)+1);render()})}
function act(a){if(a==='offline'){state.offline=!state.offline;render();return}if(a==='cart'){state.mobileCart=true;render();return}if(a==='closecart'){state.mobileCart=false;render();return}if(a==='pay'){if(!units())return;state.overlay='payment';state.mobileCart=false;state.tender=Math.max(2000,total());render();return}if(a==='closeoverlay'){state.overlay=null;render();return}if(a==='confirm'){if(state.overlay!=='payment'||state.tender<total()||!units())return;state.receipt={total:total(),tender:state.tender,cart:{...state.cart}};state.overlay='receipt';render();return}if(a==='new'){state.cart={};state.receipt=null;state.overlay=null;render();return}if(a==='clear'){if(confirm('Clear this synthetic order?')){state.cart={};render()}return}if(a==='print'){window.print();return}if(a==='enter'){state.screen='pos';render();return}if(a==='sync'){toast('Simulation only: a real sync worker is not implemented.');return}if(a==='external'){toast('External payment recording is specified, not implemented in this study.');return}if(a==='hold'){toast('Held-cart persistence belongs to the implementation, not this study.');return}if(a==='scan'){toast('Use product names/SKUs here. Hardware barcode testing is future work.');return}if(a==='update'){toast('Update lifecycle is a design state. No service worker is registered.');return}toast('Read-only design control. See the implementation specification.');}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){state.overlay=null;state.mobileCart=false;render()}if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#search')?.focus()}if(e.key==='Tab'&&state.overlay){const els=[...document.querySelectorAll('.dialog button:not(:disabled),.dialog input:not(:disabled),.dialog select:not(:disabled)')];if(els.length){let first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});
render();
